table Customer
	lineageTag: f59f013e-11da-4827-8041-4aa72130fe88

	column CustomerKey
		dataType: string
		lineageTag: 5caf2fee-27d8-440a-9fff-94f0cb423313
		summarizeBy: none
		sourceColumn: CustomerKey

		annotation SummarizationSetBy = Automatic

	column 'Customer ID'
		dataType: string
		lineageTag: b0dbbfdc-de97-4873-ae70-205a9399542a
		summarizeBy: none
		sourceColumn: Customer ID

		annotation SummarizationSetBy = Automatic

	column Customer
		dataType: string
		lineageTag: e13b439f-3e89-4a1f-aa0c-3b62b1509ff3
		summarizeBy: none
		sourceColumn: Customer

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 5998493f-214f-42f4-94f9-bab5bc49d98a
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State-Province
		dataType: string
		lineageTag: 142cfc5d-f51e-4bcf-a4b0-4b77f7e4e7f7
		summarizeBy: none
		sourceColumn: State-Province

		annotation SummarizationSetBy = Automatic

	column Country-Region
		dataType: string
		lineageTag: c05496d3-e98e-488e-aff2-147a0a6eb9d2
		summarizeBy: none
		sourceColumn: Country-Region

		annotation SummarizationSetBy = Automatic

	column 'Postal Code'
		dataType: string
		lineageTag: fb6ca205-4e4e-42b5-9daf-13b9b6b17703
		summarizeBy: none
		sourceColumn: Postal Code

		annotation SummarizationSetBy = Automatic

	partition Customer = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\ANKIMHAT\Downloads\AdventureWorks Sales_A.xlsx"), null, true),
				    Customer_Sheet = Source{[Item="Customer",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Customer_Sheet, [PromoteAllScalars=true])
				in
				    #"Promoted Headers"

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navigation

