table Product
	lineageTag: 36c80acb-9836-495d-9794-1ac4bc82d0c2

	column ProductKey
		dataType: string
		lineageTag: 0763db9b-5820-42e1-b2a2-4ea8cd91910e
		summarizeBy: none
		sourceColumn: ProductKey

		annotation SummarizationSetBy = Automatic

	column SKU
		dataType: string
		lineageTag: acb01b18-f02d-45e9-9f14-7c4574106bad
		summarizeBy: none
		sourceColumn: SKU

		annotation SummarizationSetBy = Automatic

	column Product
		dataType: string
		lineageTag: a6f16e80-767e-4d2e-ab99-b948d3099bf0
		summarizeBy: none
		sourceColumn: Product

		annotation SummarizationSetBy = Automatic

	column 'Standard Cost'
		dataType: string
		lineageTag: 222a4ef5-9438-42e0-a600-c14b50f20785
		summarizeBy: none
		sourceColumn: Standard Cost

		annotation SummarizationSetBy = Automatic

	column Color
		dataType: string
		lineageTag: f9d22a9f-b0af-4753-92e8-93b239d86641
		summarizeBy: none
		sourceColumn: Color

		annotation SummarizationSetBy = Automatic

	column 'List Price'
		dataType: string
		lineageTag: 4dc0e900-5a13-4d04-984c-2986add21833
		summarizeBy: none
		sourceColumn: List Price

		annotation SummarizationSetBy = Automatic

	column Model
		dataType: string
		lineageTag: ddb80b1d-6ba4-40c3-b292-5a9099ec722a
		summarizeBy: none
		sourceColumn: Model

		annotation SummarizationSetBy = Automatic

	column Subcategory
		dataType: string
		lineageTag: 6f669792-2cb9-4347-ac3c-e39d362c0603
		summarizeBy: none
		sourceColumn: Subcategory

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: b94a0ea4-16e4-4b21-abc0-8aaf5a660f2b
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	partition Product = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\ANKIMHAT\Downloads\AdventureWorks Sales_A.xlsx"), null, true),
				    Product_Sheet = Source{[Item="Product",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Product_Sheet, [PromoteAllScalars=true])
				in
				    #"Promoted Headers"

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navigation

