table 'User Mapping'
	lineageTag: ec21a140-ab98-41de-88f1-b87d5c555e15

	column 'First Name'
		dataType: string
		lineageTag: a2a35e2a-6006-4516-9921-c884b51b834d
		summarizeBy: none
		sourceColumn: First Name

		annotation SummarizationSetBy = Automatic

	column 'Email Address'
		dataType: string
		lineageTag: 26c4dfb1-92eb-4cb9-90c9-f9660d069526
		summarizeBy: none
		sourceColumn: Email Address

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: 7e9bfa20-975c-46e3-84d4-ee3f1ab17e9d
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	partition 'User Mapping' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\ANKIMHAT\Downloads\AdventureWorks Sales_A.xlsx"), null, true),
				    #"User Mapping_Sheet" = Source{[Item="User Mapping",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"User Mapping_Sheet", [PromoteAllScalars=true]),
				    #"Removed Blank Rows" = Table.SelectRows(#"Promoted Headers", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null})))
				in
				    #"Removed Blank Rows"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

